name: ble2301_example
description: Demonstrates how to use the ble2301 plugin.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  ble2301:
    path: ../
  get: 4.1.3
  shared_preferences: 2.1.0
  dio: 4.0.0
  archive: 3.1.6
  path_provider: 2.0.0
  permission_handler: 10.2.0
  flutter_blue_elves: 0.1.9
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
