import 'package:get/get.dart';

class Messages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'zh_CN': {
      '基础信息': '基础信息',
      '设备信息': '设备信息',
      '详细历史数据': '详细历史数据',
      '总历史数据': '计步总数据',
      '心率历史数据': '心率历史数据',
      '自动心率区间': '自动心率区间',
      '闹钟': '闹钟',
      '久坐提醒': '久坐提醒',
      '通知提醒': '通知提醒',
      '设置目标': '设置目标',
      '血氧数据': '血氧数据',
      '社交提醒': '社交提醒',
      '温度历史': '温度历史',
      '健康测量控制': '健康测量控制',
      '进入拍照模式': '进入拍照模式',
      '退出拍照模式': '退出拍照模式',
      '清除手环数据': '清除手环数据',
      '温度单位切换': '温度单位切换',
      '搜索': '搜索',
      '停止': '停止',
      '1939W测试Demo': '2301Demo',
      '连接设备': '连接设备',
      '开始运动':'开始运动',
      '锻炼数据':'锻炼数据',
      'Hrv数据':'Hrv数据',
      '运动模式':'运动模式',
      '连接中':'连接中',
      '设置手环时间':'设置手环时间',
      '获取手环时间':'获取手环时间',
      '基础信息设置':'基础信息设置',
      '性别':'性别',
      '年龄':'年龄',
      '身高':'身高',
      '体重':'体重',
      '步长':'步长',
      '男':'男',
      '女':'女',
      '设置个人信息':'设置个人信息',
      '获取个人信息':'获取个人信息',
      '没有输入年龄':'没有输入年龄',
      '没用输入身高':'没用输入身高',
      '没有输入体重':'没有输入体重',
      '初始化':'初始化',
      '电量':'电量',
      '蓝牙Mac地址':'蓝牙Mac地址',
      '固件版本':'固件版本',
      'MCU重启':'MCU重启',
      '进入升级模式':'进入升级模式',
      '距离单位':'距离单位',
      '时间模式':'时间模式',
      '千米':'千米',
      '英里':'英里',
      '12小时':'12小时',
      '24小时':'24小时',
      '抬手亮屏开关':'抬手亮屏开关',
      '华氏度/摄氏度':'华氏度/摄氏度',
      '夜间模式':'夜间模式',
      '天气开关':'天气开关',
      '表盘选择':'表盘选择',
      '基础心率必须大于40':'基础心率必须大于40',
      '设置设备信息':'设置设备信息',
      '获取设备信息':'获取设备信息',
      '手环震动频率':'手环震动频率',
      '设置':'设置',
      '获取':'获取',
      '提示':'提示',
      '出厂重置将清除设备中的所有数据，请确认是否要重置？':'出厂重置将清除设备中的所有数据，请确认是否要重置？',
      '设备未连接':'设备未连接',
      '步数':'步数',
      '睡眠':'睡眠',
      '读取':'读取',
      '删除':'删除',
      '同步中':'同步中',
      '心率/动态':'心率/动态',
      '单次心率/静态':'单次心率/静态',
      '无数据':'无数据',
      '关闭':'关闭',
      '一直开启':'一直开启',
      '间隔开启':'间隔开启',
      '周一':'周一',
      '周二':'周二',
      '周三':'周三',
      '周四':'周四',
      '周五':'周五',
      '周六':'周六',
      '周日':'周日',
      '星期一':'周一',
      '星期二':'周二',
      '星期三':'周三',
      '星期四':'周四',
      '星期五':'周五',
      '星期六':'周六',
      '星期日':'周日',
      '间隔时间':'间隔时间',
      '分钟':'分钟',
      '秒':'秒',
      '开始时间':'开始时间',
      '结束时间':'结束时间',
      '星期选择':'星期选择',
      '添加':'添加',
      '刷新':'刷新',
      '编辑':'编辑',
      '开关':'开关',
      '时间':'时间',
      '普通':'普通',
      '吃药':'吃药',
      '喝水':'喝水',
      '保存':'保存',
      '闹钟类型':'闹钟类型',
      '最小间隔':'最小间隔',
      '步':'步',
      '是否要删除该闹钟?':'是否要删除该闹钟?',
      '发送':'发送',
      '请输入内容':'请输入内容',
      '跑步':'跑步','骑车':'骑车','羽毛球':'羽毛球','足球':'足球','网球':'网球','瑜伽':'瑜伽'
      ,'呼吸':'呼吸','舞蹈':'舞蹈','篮球':'篮球','郊游野游':'郊游野游','锻炼':'锻炼',
      '板球':'板球','徒步旅行':'徒步旅行','有氧运动':'有氧运动','乒乓球':'乒乓球','跳绳':'跳绳',
      '仰卧起坐':'仰卧起坐','排球':'排球',
      '开始':'开始',
      '暂停':'暂停',
      '继续':'继续',
      '获取温度数据(主页面)':'获取温度数据(主页面)',
      '获取温度数据(测试页面)':'获取温度数据',
      '删除数据':'删除数据',
      '扫描间隔':'扫描间隔',
      '扫描时长':'扫描时长',
      '温度':'温度',
      'Hrv':'Hrv',
      '心率':'心率',
      '血氧':'血氧',
      '温度开关':'温度开关',
      '社交距离开关':'社交距离开关',
      '表盘选择(1-10)':'表盘选择(1-10)',
      '屏幕亮度(1-15)':'屏幕亮度(1-15)',
      '语言切换':'语言切换',
      '中文':'中文',
      '英文':'英文',
      '手动血氧数据':'手动血氧数据',
      '自动血氧数据':'自动血氧数据',
      '天气设置':'天气设置',
      '天气Id (0-38 或 99)':'天气Id (0-38 或 99)',
      '当前温度':'当前温度',
      '当天最高温度':'当天最高温度',
      '当天最低温度':'当天最低温度',
      '地点':'地点',
      '二维码':'二维码',
      'Ecg和Ppg':'Ecg和Ppg',
      'Ecg历史':'Ecg历史',
      'EcgPpg状态':'EcgPpg状态',
      '血糖':'血糖',
      '血压校准2166|2206|2209':'血压校准2166|2206|2209',
      '女性健康2166|2206|2209':'女性健康2166|2206|2209',
      '怀孕周期':'怀孕周期',
      '女性健康':'女性健康',
      '设置呼吸':'设置呼吸',
      '女性健康信息设置':'女性健康信息设置',
      '经期(天)':'经期(天)',
      '周期(天)':'周期(天)',
      '日期选择':'日期选择',
      '目标步数(步)':'目标步数(步)',
      '目标距离(千米)':'目标距离(千米)',
      '卡路里(千卡)':'卡路里(千卡)',
      '睡眠目标':'睡眠目标',
      '小时':'小时',
      '怀孕周期信息设置':'怀孕周期信息设置',
      '读取所有数据':'读取所有数据',
      '根据时间获取数据':'根据时间获取数据',
      '日期':'日期',
      '开启实时计步':'开启实时计步',
      'PPI' : 'PPI',
      '进度':'进度',
      '开始测量':'开始测量',
      '结束测量':'结束测量',
      'Hrv测量时长':'Hrv测量时长',
      '设置时长':'设置时长',
      '关闭蓝牙':'关闭蓝牙',
      '蓝牙设置':'蓝牙设置'
    },
    'en_US': {
      '基础信息': 'Basic information',
      '设备信息': 'Device Information',
      '详细历史数据': 'Detailed historical data',
      '总历史数据': 'Total historical data',
      '心率历史数据': 'Heart rate historical data',
      '自动心率区间': 'Automatic heart rate interval',
      '闹钟': 'alarm clock',
      '久坐提醒': 'Sedentary reminder',
      '通知提醒': 'Notification Reminder',
      '设置目标': 'Set goals',
      '血氧数据': 'Blood oxygen data',
      '社交提醒': 'Social Reminder',
      '温度历史': 'Temperature History',
      '健康测量控制': 'Health measurement control',
      '进入拍照模式': 'Enter the photographing mode',
      '退出拍照模式': 'Exit photographing mode',
      '清除手环数据': 'Clear bracelet data',
      '温度单位切换': 'Temperature unit switching',
      '搜索': 'Scan',
      '停止': 'Stop',
      '1939W测试Demo': '2301Test',
      '连接设备': 'Connect device',
      '开始运动':'Start Moving',
      '锻炼数据':'Exercise Data',
      'Hrv数据':'Hrv Data',
      '运动模式':'Sport Mode',
      '连接中':'Connecting',
      '设置手环时间':'Set Time',
      '获取手环时间':'Get Time',
      '基础信息设置':'Basic Information Set',
      '性别':'Sex',
      '年龄':'Age',
      '身高':'Height',
      '体重':'Weight',
      '步长':'Stride',
      '男':'Male',
      '女':'Female',
      '设置个人信息':'Set Personal Information',
      '获取个人信息':'Get Personal Information',
      '没有输入年龄':'No age entered',
      '没用输入身高':'No height entered',
      '没有输入体重':'No weight entered',
      '初始化':'Factory Reset',
      '电量':'Battery',
      '蓝牙Mac地址':'Mac of The Ble',
      '固件版本':'Firmware version',
      'MCU重启':'Mcu Reset',
      '进入升级模式':'Enter Ota',
      '距离单位':'Distance unit',
      '时间模式':'Time mode',
      '千米':'Km',
      '英里':'Mile',
      '12小时':'12H',
      '24小时':'24H',
      '抬手亮屏开关':'Hand up light screen switch',
      '华氏度/摄氏度':'Fahrenheit/Celsius',
      '夜间模式':'Night Mode',
      '天气开关':'Weather switch',
      '表盘选择':'Dial selection',
      '基础心率必须大于40':'Base Heart > 40',
      '设置设备信息':'Set Device Info',
      '获取设备信息':'Get Device Info',
      '手环震动频率':'Motor Vibration',
      '设置':'Set',
      '获取':'Get',
      '提示':'Tip',
      '出厂重置将清除设备中的所有数据，请确认是否要重置？':'Factory Reset will clear all the data in the device,  please confirm that you want to reset?',
      '设备未连接':'Device not connected',
      '步数':'Step Number',
      '睡眠':'Sleep',
      '读取':'Read',
      '删除':'Delete',
      '同步中':'Synchronizing',
      '心率/动态':'Heart Rate/Dynamic',
      '单次心率/静态':'Single heart rate/static',
      '无数据':'No Data',
      '关闭':'Close',
      '一直开启':'Always Open',
      '间隔开启':'Intermittent',
      '周一':'Monday',
      '周二':'Tuesday',
      '周三':'Wednesday',
      '周四':'Thursday',
      '周五':'Friday',
      '周六':'Saturday',
      '周日':'Sunday',
      '星期一':'Mon',
      '星期二':'The',
      '星期三':'Wed',
      '星期四':'Thu',
      '星期五':'Fri',
      '星期六':'Sat',
      '星期日':'Sun',
      '间隔时间':'Interval Time',
      '分钟':'Minute',
      '秒':'Second',
      '开始时间':'Start Time',
      '结束时间':'End Time',
      '星期选择':'Week Choose',
      '添加':'Add',
      '刷新':'Refresh',
      '编辑':'Edit',
      '开关':'Switch',
      '时间':'Time',
      '普通':'Normal',
      '吃药':'Medicine',
      '喝水':'Drink',
      '保存':'Save',
      '闹钟类型':'Clock Type',
      '最小间隔':'Minimal Interval',
      '步':'Step',
      '是否要删除该闹钟?':'Do you want to delete this alarm clock?',
      '发送':'Send',
      '请输入内容':'Please enter content',
      '跑步':'Run','骑车':'Cycling','羽毛球':'Badminton','足球':'Soccer','网球':'Tennis',
      '瑜伽':'Yoga',
      '呼吸':'Breathe','舞蹈':'Dance','篮球':'Basketball','郊游野游':'Walk','锻炼':'Workout',
      '板球':'Cricket','徒步旅行':'Hiking','有氧运动':'Aerobics','乒乓球':'Ping-Pong','跳绳':'Rope Jump',
      '仰卧起坐':'Sit-ups','排球':'Volleyball',
      '开始':'Start',
      '暂停':'Suspend',
      '继续':'Continue',
      '获取温度数据(主页面)':'Obtain temperature data (main page)',
      '获取温度数据(测试页面)':'Obtain temperature data',
      '删除数据':'Delete data',
      '扫描间隔':'Scan interval',
      '扫描时长':'Scan duration',
      '温度':'Temperature',
      'Hrv':'Hrv',
      '心率':'Heart Rate',
      '血氧':'Blood oxygen',
      '温度开关':'Temp Switch',
      '社交距离开关':'Social distance switch',
      '表盘选择(1-10)':'Dial selection(1-10)',
      '屏幕亮度(1-15)':'Screen brightness(1-15)',
      '语言切换':'Language switching',
      '中文':'Chinese',
      '英文':'English',
      '手动血氧数据':'Manual blood oxygen data',
      '自动血氧数据':'Automatic blood oxygen data',
      '天气设置':'Weather settings',
      '天气Id (0-38 或 99)':'Weather Id (0-38 or 99)',
      '当前温度':'Current temperature',
      '当天最高温度':'The highest temperature of the day',
      '当天最低温度':'The lowest temperature of the day',
      '地点':'place',
      '二维码':'QR code',
      'Ecg和Ppg':'Ecg and Ppg',
      'Ecg历史':'Ecg History',
      'EcgPpg状态':'EcgPpg status',
      '血糖':'blood sugar',
      '血压校准2166|2206|2209':'Blood pressure calibration 2166|2206|2209',
      '女性健康2166|2206|2209':'Women\'s Health 2166|2206|2209',
      '怀孕周期':'Pregnancy cycle',
      '设置呼吸':'Set Breathing',
      '女性健康':'Women\'s Health',
      '女性健康信息设置':'Women\'s Health Information Settings',
      '经期(天)':'Menstrual period (days)',
      '周期(天)':'Period (days)',
      '日期选择':'Date selection',
      '目标步数(步)':'Target Steps (Steps)',
      '目标距离(千米)':'Target distance (km)',
      '卡路里(千卡)':'Calories (kcal)',
      '睡眠目标':'Sleep goals',
      '小时':'Hour',
      '怀孕周期信息设置':'Pregnancy cycle information settings',
      '读取所有数据':'Read all data',
      '根据时间获取数据':'Obtain data based on time',
      '日期':'date',
      '开启实时计步':'Enable real-time step counting',
      'PPI' : 'PPI',
      '进度':'progress',
      '开始测量':'start',
      '结束测量':'end',
      'Hrv测量时长':'Hrv measurement duration',
      '设置时长':'Set duration',
      '关闭蓝牙':'Turn off Bluetooth',
      '蓝牙设置':'Bluetooth Settings'
    }
  };
}